# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ''
author_name: ''
cloud_provider: vercel
contract_name: hello_world
deployment_language: typescript
ide_jetbrains: false
ide_vscode: true
preset_name: production
project_name: algohub-poc
python_linter: ruff
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

