/* Make sure these values stay consistent with _media-queries.scss */
const SMALL_SCREEN_BREAKPOINT = 935
const XSMALL_SCREEN_BREAKPOINT = 767
const XXSMALL_SCREEN_BREAKPOINT = 560
const MID_RANGE_SCREEN_BREAKPOINT = 1160

export { SMALL_SCREEN_BREAKPOINT, XSMALL_SCREEN_BREAKPOINT, XXSMALL_SCREEN_BREAKPOINT, MID_RANGE_SCREEN_BREAKPOINT }
