name: Backend CI

on:
  workflow_call:

jobs:
  checks:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install algokit
        run: pipx install algokit

      - name: Start LocalNet
        run: algokit localnet start

      - name: Bootstrap dependencies
        run: algokit bootstrap all
        working-directory: ./backend

      - name: Configure git
        shell: bash
        working-directory: ./backend
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Build smart contracts
        working-directory: ./backend
        run: npm run build

      - name: Run tests
        working-directory: ./backend
        shell: bash
        run: |
          set -o pipefail
          npm run test

      - name: Check output stability of the smart contracts
        shell: bash
        working-directory: ./backend
        run: |
          # Add untracked files as empty so they come up in diff
          git add -N ./contracts/artifacts
          # Error out if there are any changes in teal after generating output
          git diff --exit-code --minimal ./contracts/artifacts || (echo "::error ::Smart contract artifacts have changed, ensure committed artifacts are up to date" && exit 1);
